### ISSUE TITLE
The code cannot be activated

### ISSUE THREAD

**Issue by yakirdayan** [Zontex/red-alert#3] opened 2023-02-27 20:33 UTC
Traceback (most recent call last):
  File "c:\Users\User\Desktop\python-red-alert-master\src\main.py", line 150, in <module>
    main()
  File "c:\Users\User\Desktop\python-red-alert-master\src\main.py", line 108, in main
    alert = RedAlert()
  File "c:\Users\User\Desktop\python-red-alert-master\src\main.py", line 15, in __init__
    self.locations = self.get_locations_list()
  File "c:\Users\User\Desktop\python-red-alert-master\src\main.py", line 83, in get_locations_list
    f = open('targets.json')
FileNotFoundError: [Errno 2] No such file or directory: 'targets.json'

**Comment by Zontex** [comment] 2023-02-28 00:06
Did you put targets.json in the directory? You need to modify the path on windows perhaps to fit the right path for targets.json.

**Comment by Zontex** [comment] 2023-02-28 00:18
Closing because not a bug, make sure you put the file in the directory and as you are using windows, mention the complete file path.

**Closed as completed by Zontex** 2023-02-28 00:19 UTC

**Comment by yakirdayan** [comment] 2023-02-28 13:46
@Zontex 

When I multiply the Main file and put alert link to perform "tests" I get the following error

Traceback (Most Recent Call Last):
   File "C: \ User's \ User \ Desktop \ Python-Red-Mold-Master \ Src \ Main1.py", LINE 151, in <mDule>
     Main ()
   File "C: \ Use \ User \ Desktop \ Python-Red-Hert-Master \ Src \ Main1.py", LINE 119, in Main
     Red_alerts = Alert.get_red_Alerts ()
   File "C: \ Use \ User \ Desktop \ Python-Rred-Bald-Master \ Src \ Main1.py", LINE 93, in Get_RED_ALRTS
     Alerts = R.Content.decode ("UTF-8"). Replace ("\ n", "). Replace (" \ r ",")
Unicodedecodeperror: 'Utf-8

The format of the data I introduced in the JSON file is the data that appears in the Readme.D file.
You can explain why I get this error only when I replace the Home Front Command's link to the link with which I do "tests"
